import mongoose from "mongoose";

const BookSchema = new mongoose.Schema(
  {
    isbn: String,
    thumb: String,
    title: [String],
    category: String,
    subCategory: String,
    writer: [String],
    translator: [String],
    editor: [String],
    publisher: String,
    importedCountry: String,
    price: Number,
    pages: Number,
    stock: Number,
    desc: [String],
    status: { type: String, default: "published" },
    sold: { type: Number, default: 0 },
    binding: String,
    publishedYear: String,
    paperType: String,
    volume: String,
    part: String,
    showCategory: { type: Boolean, default: true },
    showSubCategory: { type: Boolean, default: true },
    showWriters: { type: Boolean, default: true },
    showEditors: { type: Boolean, default: true },
    showTranslators: { type: Boolean, default: true },
    showImport: { type: Boolean, default: true },
    showPublisher: { type: Boolean, default: true },
    showPages: { type: Boolean, default: true },
    showPrice: { type: Boolean, default: true },
    showPieces: { type: Boolean, default: true },
    showStatus: { type: Boolean, default: true },
    showSummary: { type: Boolean, default: true },
    showPapertype: { type: Boolean, default: true },
    showBinding: { type: Boolean, default: true },
    showPublishYear: { type: Boolean, default: true },
    showVolume: { type: Boolean, default: true },
    showPart: { type: Boolean, default: true },
  },
  { timestamps: true }
);

export default mongoose.models.Book || mongoose.model("Book", BookSchema, "books");
