import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const uniSans = localFont({
  src: [
    { path: "../../public/fonts/uni-sans/Uni Sans Thin.otf", weight: "200", style: "normal" },
    { path: "../../public/fonts/uni-sans/Uni Sans Thin Italic.otf", weight: "200", style: "italic" },
    { path: "../../public/fonts/uni-sans/Uni Sans Heavy.otf", weight: "800", style: "normal" },
    { path: "../../public/fonts/uni-sans/Uni Sans Heavy Italic.otf", weight: "800", style: "italic" },
  ],
  variable: "--font-uni-sans",
  display: "swap",
});

const segoeUi = localFont({
  src: [
    { path: "../../public/fonts/uni-sans/Uni Sans Thin.otf", weight: "200", style: "normal" },
    { path: "../../public/fonts/uni-sans/Uni Sans Thin Italic.otf", weight: "200", style: "italic" },
    { path: "../../public/fonts/uni-sans/Uni Sans Heavy.otf", weight: "800", style: "normal" },
    { path: "../../public/fonts/uni-sans/Uni Sans Heavy Italic.otf", weight: "800", style: "italic" },
  ],
  variable: "--font-uni-sans",
  display: "swap",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${segoeUi.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
